# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_accfollowing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accfollowing',
            name='followee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee_set', to='main.account'),
        ),
        migrations.AlterField(
            model_name='accfollowing',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_set', to='main.account'),
        ),
        migrations.AlterField(
            model_name='image',
            name='identifier',
            field=models.CharField(default='default.png', max_length=200),
        ),
    ]
